[project]
name = "arrow-to-the-knee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "flask>=3.1.0",
    "flask-login>=0.6.3",
    "python-dotenv>=1.0.1",
    "werkzeug>=3.1.3",
]
